# ============================================================================
# Space Captain Makefile
# ============================================================================
# This project uses a unified build structure where source files are included
# directly into the main compilation unit (see CLAUDE.md for details)

# ============================================================================
# Configuration
# ============================================================================

# Compiler settings
CC = gcc
CFLAGS_COMMON = -D_DEFAULT_SOURCE -std=c18 -pedantic -Wall -Wextra -g -MMD -MP
CFLAGS_DEBUG = $(CFLAGS_COMMON) -O0
CFLAGS_RELEASE = $(CFLAGS_COMMON) -O3
CFLAGS = $(CFLAGS_DEBUG)  # Default to debug
LDFLAGS = -lpthread

# Build settings
TAG ?= pre
HOME := $(shell echo $$HOME)
PREFIX ?= $(HOME)/.local

# Directory structure
SRC_DIR = src
TST_DIR = tests
OBJ_DIR = obj
BIN_DIR = bin
DAT_DIR = data

# ============================================================================
# File Definitions
# ============================================================================

# Main source files (unified build - each includes its dependencies)
SERVER_MAIN = $(SRC_DIR)/server.c
CLIENT_MAIN = $(SRC_DIR)/client.c

# Test files
TEST_SRCS = $(wildcard $(TST_DIR)/*_tests.c)
TEST_BINS = $(patsubst $(TST_DIR)/%.c,$(BIN_DIR)/%,$(TEST_SRCS))
TEST_OBJS = $(patsubst $(TST_DIR)/%.c,$(OBJ_DIR)/%.o,$(TEST_SRCS))

# Object files for debug and release builds
SERVER_OBJ_DEBUG = $(OBJ_DIR)/debug/server.o
CLIENT_OBJ_DEBUG = $(OBJ_DIR)/debug/client.o
SERVER_OBJ_RELEASE = $(OBJ_DIR)/release/server.o
CLIENT_OBJ_RELEASE = $(OBJ_DIR)/release/client.o

# Dependency files (generated by -MMD -MP)
DEPS = $(SERVER_OBJ_DEBUG:.o=.d) $(CLIENT_OBJ_DEBUG:.o=.d) \
       $(SERVER_OBJ_RELEASE:.o=.d) $(CLIENT_OBJ_RELEASE:.o=.d) \
       $(TEST_OBJS:.o=.d)

# ============================================================================
# Primary Targets
# ============================================================================

# Default target - build debug versions
.PHONY: all
all: server client

# Build individual debug targets
.PHONY: server
server: $(BIN_DIR)/server

.PHONY: client
client: $(BIN_DIR)/client

# Build release versions
.PHONY: release
release:
	@$(MAKE) clean
	@$(MAKE) $(BIN_DIR)/server-release $(BIN_DIR)/client-release

# ============================================================================
# Build Rules - Debug
# ============================================================================

# Debug executables
$(BIN_DIR)/server: $(SERVER_OBJ_DEBUG) | $(BIN_DIR)
	$(CC) $(LDFLAGS) -o $@ $^

$(BIN_DIR)/client: $(CLIENT_OBJ_DEBUG) | $(BIN_DIR)
	$(CC) $(LDFLAGS) -o $@ $^

# Debug object files
$(OBJ_DIR)/debug/server.o: $(SERVER_MAIN) | $(OBJ_DIR)/debug
	$(CC) $(CFLAGS_DEBUG) -I$(SRC_DIR) -c -o $@ $<

$(OBJ_DIR)/debug/client.o: $(CLIENT_MAIN) | $(OBJ_DIR)/debug
	$(CC) $(CFLAGS_DEBUG) -I$(SRC_DIR) -c -o $@ $<

# ============================================================================
# Build Rules - Release
# ============================================================================

# Release executables (with versioning)
$(BIN_DIR)/server-release: $(SERVER_OBJ_RELEASE) | $(BIN_DIR)
	@VERSION=$$(cat .VERSION); \
	DATETIME=$$(date +%Y%m%dT%H%M%S%z); \
	FULL_VERSION="$$VERSION-$(TAG).$$DATETIME"; \
	$(CC) $(LDFLAGS) -o $(BIN_DIR)/server-$$FULL_VERSION $^; \
	ln -sf server-$$FULL_VERSION $@

$(BIN_DIR)/client-release: $(CLIENT_OBJ_RELEASE) | $(BIN_DIR)
	@VERSION=$$(cat .VERSION); \
	DATETIME=$$(date +%Y%m%dT%H%M%S%z); \
	FULL_VERSION="$$VERSION-$(TAG).$$DATETIME"; \
	$(CC) $(LDFLAGS) -o $(BIN_DIR)/client-$$FULL_VERSION $^; \
	ln -sf client-$$FULL_VERSION $@

# Release object files
$(OBJ_DIR)/release/server.o: $(SERVER_MAIN) | $(OBJ_DIR)/release
	$(CC) $(CFLAGS_RELEASE) -I$(SRC_DIR) -c -o $@ $<

$(OBJ_DIR)/release/client.o: $(CLIENT_MAIN) | $(OBJ_DIR)/release
	$(CC) $(CFLAGS_RELEASE) -I$(SRC_DIR) -c -o $@ $<

# ============================================================================
# Test Targets
# ============================================================================

.PHONY: tests
tests: $(TEST_BINS)

.PHONY: run-tests
run-tests: tests server client
	@for test in $(TEST_BINS); do \
		echo "Running $$test..."; \
		$$test || exit 1; \
	done

# Test executables
$(BIN_DIR)/%_tests: $(OBJ_DIR)/%_tests.o | $(BIN_DIR)
	$(CC) $(LDFLAGS) -o $@ $^

# Test object files
$(OBJ_DIR)/%_tests.o: $(TST_DIR)/%_tests.c | $(OBJ_DIR)
	$(CC) $(CFLAGS_DEBUG) -I$(SRC_DIR) -c -o $@ $<

# ============================================================================
# Development Targets
# ============================================================================

# Run targets
.PHONY: run-server
run-server: server | $(DAT_DIR)
	$(BIN_DIR)/server

.PHONY: run-client
run-client: client
	$(BIN_DIR)/client

# Debug with GDB
.PHONY: debug-server
debug-server: server
	gdb $(BIN_DIR)/server

.PHONY: debug-client
debug-client: client
	gdb $(BIN_DIR)/client

# Code formatting
.PHONY: fmt
fmt:
	@find . -path ./tst/vendor -prune -o \( -name "*.c" -o -name "*.h" \) -type f -print | while read file; do \
		echo "Formatting: $$file"; \
		clang-format -i "$$file"; \
	done

# Update CLI tools
.PHONY: update-tools
update-tools:
	npm upgrade -l @google/gemini-cli
	npm upgrade -l @anthropic-ai/claude-code
	npm upgrade -l @openai/codex

# Install CLI tools
.PHONY: install-tools
install-tools:
	npm install -l @google/gemini-cli
	npm install -l @anthropic-ai/claude-code
	npm install -l @openai/codex

# Architecture diagram
# Regenerate when any source files change
SRC_FILES = $(wildcard $(SRC_DIR)/*.c $(SRC_DIR)/*.h)

.PHONY: dot
dot: docs/arch.png

docs/arch.png: arch.dot $(SRC_FILES)
	dot -Tpng $< -o $@

# ============================================================================
# Installation & Cleanup
# ============================================================================

.PHONY: install
install: release
	@echo "Installing Space Captain to $(PREFIX)/bin"
	@install -d $(PREFIX)/bin
	@SERVER_VERSIONED=$$(basename $$(readlink -f $(BIN_DIR)/server-release)) && \
	CLIENT_VERSIONED=$$(basename $$(readlink -f $(BIN_DIR)/client-release)) && \
	echo "Installing server: $$SERVER_VERSIONED" && \
	install -m 755 $(BIN_DIR)/$$SERVER_VERSIONED $(PREFIX)/bin/$$SERVER_VERSIONED && \
	echo "Installing client: $$CLIENT_VERSIONED" && \
	install -m 755 $(BIN_DIR)/$$CLIENT_VERSIONED $(PREFIX)/bin/$$CLIENT_VERSIONED && \
	echo "Creating symlinks..." && \
	ln -sf $$SERVER_VERSIONED $(PREFIX)/bin/space-captain-server && \
	ln -sf $$CLIENT_VERSIONED $(PREFIX)/bin/space-captain-client && \
	echo "Installation complete!"

.PHONY: clean
clean:
	rm -rf $(OBJ_DIR) $(BIN_DIR)

# ============================================================================
# Version Management
# ============================================================================

.PHONY: version
version:
	@VERSION=$$(cat .VERSION); \
	DATETIME=$$(date +%Y%m%dT%H%M%S%z); \
	echo "$$VERSION-$(TAG).$$DATETIME"

.PHONY: bump-patch
bump-patch:
	@VERSION=$$(cat .VERSION); \
	MAJOR=$$(echo $$VERSION | cut -d. -f1); \
	MINOR=$$(echo $$VERSION | cut -d. -f2); \
	PATCH=$$(echo $$VERSION | cut -d. -f3); \
	NEW_PATCH=$$(($$PATCH + 1)); \
	echo "$$MAJOR.$$MINOR.$$NEW_PATCH" > .VERSION; \
	echo "Version bumped to $$(cat .VERSION)"

.PHONY: bump-minor
bump-minor:
	@VERSION=$$(cat .VERSION); \
	MAJOR=$$(echo $$VERSION | cut -d. -f1); \
	MINOR=$$(echo $$VERSION | cut -d. -f2); \
	NEW_MINOR=$$(($$MINOR + 1)); \
	echo "$$MAJOR.$$NEW_MINOR.0" > .VERSION; \
	echo "Version bumped to $$(cat .VERSION)"

.PHONY: bump-major
bump-major:
	@VERSION=$$(cat .VERSION); \
	MAJOR=$$(echo $$VERSION | cut -d. -f1); \
	NEW_MAJOR=$$(($$MAJOR + 1)); \
	echo "$$NEW_MAJOR.0.0" > .VERSION; \
	echo "Version bumped to $$(cat .VERSION)"


# ============================================================================
# Help Target
# ============================================================================

.PHONY: help
help:
	@echo "Space Captain Makefile"
	@echo "===================="
	@echo ""
	@echo "Primary Targets:"
	@echo "  make              Build debug server and client (default)"
	@echo "  make server       Build debug server only"
	@echo "  make client       Build debug client only"
	@echo "  make release      Build release versions with versioning"
	@echo ""
	@echo "Testing:"
	@echo "  make tests        Build all test executables"
	@echo "  make run-tests    Build and run all tests"
	@echo ""
	@echo "Development:"
	@echo "  make run-server   Build and run debug server"
	@echo "  make run-client   Build and run debug client"
	@echo "  make debug-server Debug server with GDB"
	@echo "  make debug-client Debug client with GDB"
	@echo "  make fmt          Format all code with clang-format"
	@echo ""
	@echo "Maintenance:"
	@echo "  make clean        Remove all build artifacts"
	@echo "  make install      Install release versions to PREFIX"
	@echo "  make dot          Generate architecture diagram"
	@echo "  make install-tools Install CLI tools (gemini, claude, codex)"
	@echo "  make update-tools Update CLI tools to latest versions"
	@echo ""
	@echo "Version Management:"
	@echo "  make version      Display current version"
	@echo "  make bump-patch   Increment patch version (0.0.X)"
	@echo "  make bump-minor   Increment minor version (0.X.0)"
	@echo "  make bump-major   Increment major version (X.0.0)"
	@echo ""
	@echo "Environment Variables:"
	@echo "  TAG=<tag>         Set build tag (default: pre)"
	@echo "  PREFIX=<path>     Set installation prefix (default: ~/.local)"

# ============================================================================
# Directory Creation
# ============================================================================

$(BIN_DIR) $(DAT_DIR) $(OBJ_DIR)/debug $(OBJ_DIR)/release $(OBJ_DIR):
	mkdir -p $@

# ============================================================================
# Include Dependencies
# ============================================================================

# Include auto-generated dependency files
-include $(DEPS)
